// The app's own commands are only callable from the built-in screens unless
// they're declared in an app manifest and granted by a capability - which the
// live-updated screens (served from a local origin) need. Rather than keep a
// second copy of the command list, read it from the invoke_handler in lib.rs.
fn main() {
    let lib = std::fs::read_to_string("src/lib.rs").expect("src/lib.rs");
    let handler = lib
        .split("generate_handler![")
        .nth(1)
        .and_then(|rest| rest.split(']').next())
        .expect("generate_handler! block in src/lib.rs");
    let mut commands: Vec<String> = handler
        .split(',')
        .filter_map(|entry| entry.trim().rsplit("::").next().map(str::to_string))
        .filter(|name| !name.is_empty() && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'))
        .collect();
    commands.sort();
    commands.dedup();

    let permissions: Vec<String> = commands
        .iter()
        .map(|c| format!("\"allow-{}\"", c.replace('_', "-")))
        .collect();
    std::fs::create_dir_all("permissions").expect("permissions dir");
    std::fs::write(
        "permissions/app-commands.toml",
        format!(
            "# Generated by build.rs from the commands registered in src/lib.rs.\n[[set]]\nidentifier = \"app-commands\"\ndescription = \"Every command this app defines\"\npermissions = [{}]\n",
            permissions.join(", ")
        ),
    )
    .expect("write permissions/app-commands.toml");

    // AppManifest wants 'static names; a build script can just leak them.
    let command_refs: &'static [&'static str] = Box::leak(
        commands
            .iter()
            .map(|c| &*Box::leak(c.clone().into_boxed_str()))
            .collect::<Vec<&'static str>>()
            .into_boxed_slice(),
    );
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(command_refs)),
    )
    .expect("failed to run tauri-build");
    println!("cargo:rerun-if-changed=src/lib.rs");

    // The commit this backend was built from (see launcher.rs). Without
    // watching HEAD, cargo has no reason to rerun this script for a plain
    // rebuild after a new commit (only src/lib.rs or the env var above do
    // that) - so a local `cargo build` would keep embedding a stale SHA
    // from whenever this script last actually ran.
    let git_dir = std::path::Path::new("../../.git");
    println!("cargo:rerun-if-changed={}", git_dir.join("HEAD").display());
    if let Ok(head) = std::fs::read_to_string(git_dir.join("HEAD")) {
        if let Some(ref_path) = head.trim().strip_prefix("ref: ") {
            println!("cargo:rerun-if-changed={}", git_dir.join(ref_path).display());
        }
    }

    let sha = std::env::var("RECHARGE_BUILD_SHA").ok().or_else(|| {
        std::process::Command::new("git")
            .args(["rev-parse", "HEAD"])
            .output()
            .ok()
            .filter(|o| o.status.success())
            .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
    });
    println!("cargo:rustc-env=RECHARGE_BUILD_SHA={}", sha.unwrap_or_default());
    println!("cargo:rerun-if-env-changed=RECHARGE_BUILD_SHA");

    // When this binary was compiled (UTC, GitHub's release created_at format)
    // - see launcher.rs. A SHA mismatch against the latest release doesn't by
    // itself mean an update is available: a local dev build made after that
    // release was published is also a mismatch, but isn't behind it. Comparing
    // build time against the release's created_at tells the two apart.
    println!("cargo:rustc-env=RECHARGE_BUILD_TIME={}", iso8601_now());
}

fn iso8601_now() -> String {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs() as i64)
        .unwrap_or(0);
    let days = secs.div_euclid(86400);
    let sod = secs.rem_euclid(86400);
    let (h, m, s) = (sod / 3600, (sod % 3600) / 60, sod % 60);

    // Howard Hinnant's civil_from_days (public domain): days-since-epoch -> Y/M/D.
    let z = days + 719468;
    let era = if z >= 0 { z } else { z - 146096 } / 146097;
    let doe = z - era * 146097;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146096) / 365;
    let y = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let mo = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if mo <= 2 { y + 1 } else { y };

    format!("{y:04}-{mo:02}-{d:02}T{h:02}:{m:02}:{s:02}Z")
}
