// The app's own commands are only callable from the built-in screens unless
// they're declared in an app manifest and granted by a capability - which the
// live-updated screens (served from a local origin) need. Rather than keep a
// second copy of the command list, read it from the invoke_handler in lib.rs.
fn main() {
    let lib = std::fs::read_to_string("src/lib.rs").expect("src/lib.rs");
    let handler = lib
        .split("generate_handler![")
        .nth(1)
        .and_then(|rest| rest.split(']').next())
        .expect("generate_handler! block in src/lib.rs");
    let mut commands: Vec<String> = handler
        .split(',')
        .filter_map(|entry| entry.trim().rsplit("::").next().map(str::to_string))
        .filter(|name| !name.is_empty() && name.chars().all(|c| c.is_ascii_alphanumeric() || c == '_'))
        .collect();
    commands.sort();
    commands.dedup();

    let permissions: Vec<String> = commands
        .iter()
        .map(|c| format!("\"allow-{}\"", c.replace('_', "-")))
        .collect();
    std::fs::create_dir_all("permissions").expect("permissions dir");
    std::fs::write(
        "permissions/app-commands.toml",
        format!(
            "# Generated by build.rs from the commands registered in src/lib.rs.\n[[set]]\nidentifier = \"app-commands\"\ndescription = \"Every command this app defines\"\npermissions = [{}]\n",
            permissions.join(", ")
        ),
    )
    .expect("write permissions/app-commands.toml");

    // AppManifest wants 'static names; a build script can just leak them.
    let command_refs: &'static [&'static str] = Box::leak(
        commands
            .iter()
            .map(|c| &*Box::leak(c.clone().into_boxed_str()))
            .collect::<Vec<&'static str>>()
            .into_boxed_slice(),
    );
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(command_refs)),
    )
    .expect("failed to run tauri-build");
    println!("cargo:rerun-if-changed=src/lib.rs");
}
